config/routes.rb
Rails.application.routes.draw do
<<<<<<< HEAD
  resources :patient_statuses
=======
  resources :news
>>>>>>> 11fc598adfbbc0afa1da93b30ea7823c173ab510

end

app/models/new.rb
class New < ActiveRecord::Base
end

app/models/patient_status.rb
class PatientStatus < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  before_action :set_news, only: [:show, :edit, :update, :destroy]

  # GET /news
  # GET /news.json
  def index
    @news = New.all
  end

  # GET /news/1
  # GET /news/1.json
  def show
  end

  # GET /news/new
  def new
    @news = New.new
  end

  # GET /news/1/edit
  def edit
  end

  # POST /news
  # POST /news.json
  def create
    @news = New.new(news_params)

    respond_to do |format|
      if @news.save
        format.html { redirect_to @news, notice: 'New was successfully created.' }
        format.json { render :show, status: :created, location: @news }
      else
        format.html { render :new }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /news/1
  # PATCH/PUT /news/1.json
  def update
    respond_to do |format|
      if @news.update(news_params)
        format.html { redirect_to @news, notice: 'New was successfully updated.' }
        format.json { render :show, status: :ok, location: @news }
      else
        format.html { render :edit }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news/1
  # DELETE /news/1.json
  def destroy
    @news.destroy
    respond_to do |format|
      format.html { redirect_to news_url, notice: 'New was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_news
      @news = New.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def news_params
      params.require(:news).permit(:name)
    end
end

app/controllers/patient_statuses_controller.rb
class PatientStatusesController < ApplicationController
  before_action :set_patient_status, only: [:show, :edit, :update, :destroy]

  # GET /patient_statuses
  # GET /patient_statuses.json
  def index
    @patient_statuses = PatientStatus.all
  end

  # GET /patient_statuses/1
  # GET /patient_statuses/1.json
  def show
  end

  # GET /patient_statuses/new
  def new
    @patient_status = PatientStatus.new
  end

  # GET /patient_statuses/1/edit
  def edit
  end

  # POST /patient_statuses
  # POST /patient_statuses.json
  def create
    @patient_status = PatientStatus.new(patient_status_params)

    respond_to do |format|
      if @patient_status.save
        format.html { redirect_to @patient_status, notice: 'Patient status was successfully created.' }
        format.json { render :show, status: :created, location: @patient_status }
      else
        format.html { render :new }
        format.json { render json: @patient_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patient_statuses/1
  # PATCH/PUT /patient_statuses/1.json
  def update
    respond_to do |format|
      if @patient_status.update(patient_status_params)
        format.html { redirect_to @patient_status, notice: 'Patient status was successfully updated.' }
        format.json { render :show, status: :ok, location: @patient_status }
      else
        format.html { render :edit }
        format.json { render json: @patient_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patient_statuses/1
  # DELETE /patient_statuses/1.json
  def destroy
    @patient_status.destroy
    respond_to do |format|
      format.html { redirect_to patient_statuses_url, notice: 'Patient status was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient_status
      @patient_status = PatientStatus.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def patient_status_params
      params.require(:patient_status).permit(:status_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/patient_statuses_helper.rb
module PatientStatusesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gitdemo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/news/_form.html.erb
<%= form_for(@news) do |f| %>
  <% if @news.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@news.errors.count, "error") %> prohibited this news from being saved:</h2>

      <ul>
      <% @news.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/news/edit.html.erb
<h1>Editing news</h1>

<%= render 'form' %>

<%= link_to 'Show', @news %> |
<%= link_to 'Back', news_path %>

app/views/news/index.html.erb
<h1>Listing news</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @news.each do |news| %>
      <tr>
        <td><%= news.name %></td>
        <td><%= link_to 'Show', news %></td>
        <td><%= link_to 'Edit', edit_news_path(news) %></td>
        <td><%= link_to 'Destroy', news, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New New', new_news_path %>

app/views/news/new.html.erb
<h1>New news</h1>

<%= render 'form' %>

<%= link_to 'Back', news_path %>

app/views/news/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @news.name %>
</p>

<%= link_to 'Edit', edit_news_path(@news) %> |
<%= link_to 'Back', news_path %>

app/views/patient_statuses/_form.html.erb
<%= form_for(@patient_status) do |f| %>
  <% if @patient_status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@patient_status.errors.count, "error") %> prohibited this patient_status from being saved:</h2>

      <ul>
      <% @patient_status.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :status_name %><br>
    <%= f.text_field :status_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/patient_statuses/edit.html.erb
<h1>Editing patient_status</h1>

<%= render 'form' %>

<%= link_to 'Show', @patient_status %> |
<%= link_to 'Back', patient_statuses_path %>

app/views/patient_statuses/index.html.erb
<h1>Listing patient_statuses</h1>

<table>
  <thead>
    <tr>
      <th>Status name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @patient_statuses.each do |patient_status| %>
      <tr>
        <td><%= patient_status.status_name %></td>
        <td><%= link_to 'Show', patient_status %></td>
        <td><%= link_to 'Edit', edit_patient_status_path(patient_status) %></td>
        <td><%= link_to 'Destroy', patient_status, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Patient status', new_patient_status_path %>

app/views/patient_statuses/new.html.erb
<h1>New patient_status</h1>

<%= render 'form' %>

<%= link_to 'Back', patient_statuses_path %>

app/views/patient_statuses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Status name:</strong>
  <%= @patient_status.status_name %>
</p>

<%= link_to 'Edit', edit_patient_status_path(@patient_status) %> |
<%= link_to 'Back', patient_statuses_path %>